### ISSUE TITLE
Installation of Zabbix-Template-Linux-Collectd_libvirt

### ISSUE THREAD

**Issue by alexio1313** [H-Software/Zabbix-Template-Linux-Collectd_libvirt#1]
Hi,

I am a bit confused about the deployment of the template below are the steps i have done. Please let me know if i am doing it the right way.

I have a configured Zabbix server version Zabbix 2.4.4 and it is up and running.
1. Copied  collect-libvirt-handler.pl to Zabbix Server script directory.
2. Installed packages on node server running virtual machines (yum install collectd collectd-virt perl-Collectd) 
3. Overwrite collectd.conf file on the Node server
4. Copy "zabbix-collectd.conf" To "/etc/zabbix/zabbix_agentd.d" on Node Server.

Sorry for asking in detail as per the Installation instruction it is not clear where the packages need to be installed or the scripts and conf files to be copied.

If possible please provide me with a proper installation guide for exact 

What steps needs to performs on Zabbix Server
AND
What steps needs to be performed on KVM Node where the virtual machine are hosted.

Regards,

Alex Almeida.

**Comment by czhujer** [comment]
I modified readme ..https://github.com/H-Software/Zabbix-Template-Linux-Collectd_libvirt/commit/ddc3bc15e7c171721c421d0d4299d360b93d0d18
Do you can check this?
