### ISSUE TITLE
zabbix agent does not work for collectd 5.5 or later

### ISSUE THREAD

**Issue by weihj1999** [H-Software/Zabbix-Template-Linux-Collectd_libvirt#2]
I upgrade system to rhel7.1 and insall collectd 5.5 which is different with collectd 4.2

From the release notes https://collectd.org/wiki/index.php/Version_5.5, The libvirt plugin has been renamed to virt. so this template may not work with a different data structure. 
5.4.1：
$VAR1 = {
          'plugin' => 'libvirt',
          'time' => 1447713244,
          'type' => 'virt_cpu_total',
          'host' => 'instance-00000002'
        };
5.5.0
$VAR1 = {
          'plugin' => 'virt',
          'time' => 1447729396,
          'plugin_instance' => 'instance-000000a4',
          'type' => 'virt_cpu_total',
          'host' => 'instance-000000a4'
        };
Ths scripts collect-libvirt-handler.pl which work sfor 5.4.1 does not work for 5.5.0.  

Can we upgrade the sript to support collectd 5.5.0 or later?

**Comment by czhujer** [comment]
Hi,
thanks for reporting issue(s).

Yes, we can :)

**Comment by czhujer** [comment]
Hi,

I rewrote script for collectd v5.5 (and centos7)...
~~https://github.com/H-Software/Zabbix-Template-Linux-Collectd_libvirt/blob/devel/scripts/collect-libvirt-handler-v5.pl~~
[ https://github.com/H-Software/Zabbix-Template-Linux-Collectd_libvirt/pull/6 ](https://github.com/H-Software/Zabbix-Template-Linux-Collectd_libvirt/pull/6)

Can you test it?
