### ISSUE TITLE
there are some error

### ISSUE THREAD

**Issue by linkt** [H-Software/Zabbix-Template-Linux-Collectd_libvirt#3]
hello,I use your template in my host .when I start the zabbix_agentd, the are some error:
zabbix_agentd [100337]: invalid entry [FQDNLookup true](not following "parameter=value" notation) in config file [/etc/zabbix/zabbix_agentd.d/collectd.conf], line 2.
can you tell me how can I do?

**Comment by czhujer** [comment]
Hi,

you have to put/rewrite this file ("/configs/collectd.conf") into /etc.
This is config for collectd.

I have a mistake in README.

**Comment by czhujer** [comment]
readme fixed..
https://github.com/H-Software/Zabbix-Template-Linux-Collectd_libvirt/commit/136ada4c9da28a91094109c0e047e8d9ec46e89c
