### ISSUE TITLE
Does it works with Zabbix 3.0 LTS?

### ISSUE THREAD

**Issue by s-chekanov** [H-Software/Zabbix-Template-Linux-Collectd_libvirt#7]
Or just zabbix 2?

**Comment by czhujer** [comment]
Hi,

i don't see reason for why not... 
You can try it and eventually make Issue or PR :)

I think, it depends on version of OS/collecd and etc..
https://github.com/H-Software/Zabbix-Template-Linux-Collectd_libvirt/issues/2
